seed:
  Plant:
    - { x: 0, y: 0 }
    - { x: 5, y: 4 }
    - { x: 12, y: 1 }
    - { x: 13, y: 8 }
  Herbivore:
    - { x: 0, y: 6 }
    - { x: 3, y: 10 }
    - { x: 11, y: 0 }
  Predator:
    - { x: 7, y: 5 }
    - { x: 11, y: 9 }
game_param:
  Plant:
    T_Plant_steps: 50
  Herbivore:
    T_Herbivore_steps: 30
    R_Herbivore_sight: 3
    T_cooldown_steps: 3
  Predator:
    T_Predator_steps: 40
    R_Predator_sight: 5