screen:
  width: 800
  height: 600
  cell_size: 6

colors:
  alive: [255, 255, 255]    # White for alive cells
  dead: [30, 30, 30]        # Dark gray for dead cells

seed:
  pattern_folder: "initial_patterns"    # Path to the pattern folder

game_param:
  T_plant_steps: 50
  T_herbivore_steps: 30
  R_herbivore_sight1: 5
  T_cooldown_steps: 7
  T_predator_steps: 40
